### ISSUE TITLE
Unable to set fonts with specifications

### ISSUE THREAD

**Issue by roganoalien** [zeitlings/alfred-calendar#3]
So I was testing the workflow after you posted in Reddit and I download it to try it but after the installation I got the error: `Unable to set fonts with specifications: <Product Sans> <15.0>` even though I do have installed the font thats requested on the README. 

Here are some screenshots:
Error
![Font Book_18_06_2024_01-06-15@2x](https://github.com/zeitlings/alfred-calendar/assets/6985253/aabb07da-0faf-4f2c-befb-affde580a3f9)

And the proof that I have the font installed in my mbp
![Font Book_18_06_2024_01-06-44@2x](https://github.com/zeitlings/alfred-calendar/assets/6985253/7b41933d-9392-4f0d-b987-d9c07c333d92)

**Comment by zeitlings** [comment]
Hey @roganoalien,

The SF Pro font is *just* so the icons are rendered. Otherwise, the workflow uses the font you set for your Alfred theme, which in your case appears to be Product Sans, size 15.0. I've encountered this myself once with a different font. What you are seeing is an error that NSFont throws when it tries and fails to initialize with the given parameters. Why it fails with certain fonts I don't know at the moment. 

The simplest solution should be to try a different font for your Alfred theme.

**Comment by montemartin** [comment]
I'm getting the same error (with Lexend Medium). I changed to a system font and it works fine. I've never run into this error in other workflows. Would love to get it fixed so we can use it correctly with our preferred font.

**Comment by zeitlings** [comment]
Hey @roganoalien @montemartin 

You can try again with [v2.1.0](https://github.com/zeitlings/alfred-calendar/releases/tag/v2.1.0). If you're still having trouble, feel free to share your fonts with me so I can run some tests on them.

> I've never run into this error in other workflows.

This is because none of your other workflows need to consider the font you are using.

**Comment by montemartin** [comment]
Upgrading to 2.1.0 worked to allow fonts, but I got a notification that Apple wasn't able to scan "calpp" for vulnerabilites and had to allow it to run in security preferences. That didn't happen when I ran v2.0.

**Comment by zeitlings** [comment]
> Upgrading to 2.1.0 worked to allow fonts, but I got a notification that Apple wasn't able to scan "calpp" for vulnerabilites and had to allow it to run in security preferences. That didn't happen when I ran v2.0.

@montemartin Didn't you see the permission handler pop up again? If it's not related to the Gatekeeper though, then I can't say when or why macOS decides that Alfred having permissions is not enough. That happened before though, see [first footnote](https://github.com/zeitlings/alfred-calendar?tab=readme-ov-file#user-content-fn-1-fb7f9ab190678f1bc91d7bc88b8171fb) of the readme, or directly the relevant comment in [#2](https://github.com/zeitlings/alfred-calendar/issues/2#issuecomment-2132736512)
